-- Starts on the frame immediately after pressing select to do the select skip
dofile('lode-runner-core.lua')

c.Start()

if c.CurrentLevel() ~= 34 then
    error('must be run in level 34')
end

if c.GameMode() ~= 1 then
    error('must be run in level mode')
end

local function DigRoute()
    c.UntilGoldLeft()
    c.UntilDig('Left', 'A')
    c.FallRight()
    c.UntilGoldRight()
    c.UntilDig('Left', 'A')
    c.FallRight()
    c.UntilGoldRight()
    c.UntilDig('Left', 'A')
    c.FallRight()
    c.UntilDig('Right', 'B')
    c.FallLeft()
    c.GrabLadderLeft()
    c.ClimbUntil(4)
    c.GrabLadderLeft()
    c.ClimbUntil(3)
    c.LeftFor(1)
    c.ClimbUntil(4)
    c.FinishFalling()
    c.FallLeft()
    c.GrabLadderLeft()
    c.ClimbUntil(9)
    c.LeftFor(1)
    c.GrabLadderLeft()
    c.ClimbUntil(8)
    c.GrabLadderLeft()
    c.ClimbUntil(7)
    c.GrabLadderLeft()
    c.ClimbUntil(5)
    c.GrabLadderRight('Down')
    c.ClimbUntil(6)
    c.FinishFalling()
    c.GrabLadderLeft()
    c.ClimbUntil(5)
    c.GrabLadderRight()
    c.ClimbUntil(4)
    c.GrabLadderRight('Down')
    c.ClimbUntil(5)
    c.FinishFalling()
    c.GrabLadderLeft()
    c.ClimbUntil(7)
    c.GrabLadderLeft()
    c.ClimbUntil(5)

    --c.GrabLadderRight()
    c.PushRight() --Ugh
    c.PushUpAndRight()

    c.ClimbUntil(4)
    c.GrabLadderRight()
    c.ClimbUntil(3)
    c.RightFor(1)
    c.ClimbUntil(4)
    c.FinishFalling()
    c.FallRight()
    c.GrabLadderRight()
    c.ClimbUntil(9)
    c.RightFor(1)
    c.GrabLadderRight()
    c.ClimbUntil(8)
    c.GrabLadderRight()
    c.ClimbUntil(7)
    c.GrabLadderRight()
    c.ClimbUntil(5)
    c.GrabLadderLeft()
    c.ClimbUntil(4)
    c.GrabLadderLeft('Down')
    c.ClimbUntil(5)
    c.FinishFalling()
    c.GrabLadderRight()
    c.ClimbUntil(7)
    c.GrabLadderRight()
    c.ClimbUntil(5)
    c.GrabLadderLeft('Down')
    c.ClimbUntil(6)
    c.FinishFalling()
    c.ClimbUntil(8)
    c.GrabLadderRight('Down')
    c.ClimbUntil(9)
    c.FinishFalling()
    c.RightFor(5)
    c.GrabLadderRight()
    c.ClimbUntilLevelEnd()

    return true
end

local function V5Route()
    c.UntilGoldLeft()
    c.UntilGoldLeft()
    c.UntilDig('Right', 'B')
    c.FallLeft()
    c.ClimbUntil(3)
    c.GrabLadderLeft('Down')
    c.ClimbUntil(4)
    c.FinishFalling()
    c.FallLeft()
    c.GrabLadderLeft()

    c.ClimbUntil(9)
    c.LeftFor(1)
    c.GrabLadderLeft()
    c.ClimbUntil(8)
    c.GrabLadderLeft()
    c.ClimbUntil(7)
    c.GrabLadderLeft()
    c.ClimbUntil(5)
    c.GrabLadderRight('Down')
    c.ClimbUntil(6)
    c.FinishFalling()
    c.GrabLadderLeft()
    c.ClimbUntil(5)
    c.GrabLadderRight()
    c.ClimbUntil(4)
    c.GrabLadderRight('Down')
    c.ClimbUntil(5)
    c.FinishFalling()

    c.GrabLadderLeft()
    c.ClimbUntil(7)
    c.GrabLadderLeft()
    c.ClimbUntil(5)
    c.GrabLadderRight()
    c.ClimbUntil(4)
    c.GrabLadderRight()
    c.ClimbUntil(3)
    c.GrabLadderRight('Down')
    c.ClimbUntil(5)
    c.FinishFalling()
    c.FallRight()
    c.GrabLadderRight()
    c.ClimbUntil(9)
    c.RightFor(1)
    c.GrabLadderRight()
    c.ClimbUntil(8)
    c.GrabLadderRight()
    c.ClimbUntil(7)
    c.GrabLadderRight()
    c.ClimbUntil(5)

    --c.GrabLadderLeft()
    c.PushLeft()  --ugh
    c.PushUpAndLeft()

    c.ClimbUntil(4)
    c.GrabLadderLeft('Down')
    c.ClimbUntil(5)
    c.FinishFalling()
    c.GrabLadderRight()
    c.ClimbUntil(7)
    c.GrabLadderRight()
    c.ClimbUntil(5)
    c.GrabLadderLeft('Down')
    c.ClimbUntil(6)
    c.FinishFalling()
    c.ClimbUntil(8)
    c.GrabLadderRight('Down')
    c.ClimbUntil(10)
    c.FinishFalling()
    c.RightFor(5)
    c.GrabLadderRight()
    c.ClimbUntil(1)
    c.LeftUntil(19)
    c.PushDown()
    c.FinishFalling()
    c.FallRight()
    c.FallRight()
    c.FallRight()
    c.GrabLadderRight()
    c.ClimbUntilLevelEnd()

    return true
end

-- spawn timer must be a specific range for E2 and E3 to drop gold as soon as they leave the O
while not c.IsDone() do
    c.GrabLadderLeft()
    c.ClimbUntil(1)
    c.RightUntil(6)
    c.UntilGoldRight()
    c.UntilGoldRight()
    c.LeftUntil(8)
    c.PushDown()
    c.FinishFalling()
    c.FallLeft()
    c.FallLeft()
    c.FallLeft()
    c.RightFor(2)
    c.GrabLadderRight('Down')
    c.ClimbUntil(13)

    c.WaitFor(15)
    c.Assert(c.FrameSearch(function()
        local result = c.ClimbUntil(12)
        if not result then return false end
        result = c.UntilGoldLeft()
        if not result then return false end
        result = c.UntilGoldLeft()
        if not result then return false end
        return c.RightFor(1)
    end))

    c.BestOf({
        function() return c.RightUntil(16) end,
        function()
            c.GrabLadderRight('Down')
            c.ClimbUntil(13)
            return c.RightUntil(16)
        end,
    })

    c.GrabLadderRight()
    c.ClimbUntil(12)
    c.RightFor(5)
    c.GrabLadderRight()
    c.ClimbUntil(1)
    c.LeftUntil(20)

    c.BestOf({
        DigRoute,
        V5Route,
    })

    c.Done()

    --c.Marker('lv 34 end')
end

c.Finish()
